In [2]:
import numpy as np

In [3]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr)

numpy.ndarray

In [5]:
# array의 형태(크기)를 확인
arr.shape

(10,)

In [6]:
# array의 자료형을 확인
arr.dtype

dtype('int32')

In [7]:
data = [0,1,2,3,4,5,6,7,8,9]
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [10]:
2 * a + b

array([12, 24, 36])

In [11]:
b - a

array([ 9, 18, 27])

In [12]:
a == 2

array([False,  True, False])

In [13]:
b > 10

array([False,  True,  True])

In [14]:
(a == 2) & (b > 10)

array([False,  True, False])

In [16]:
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
len(c)

2

In [18]:
len(c[0])

3

In [19]:
abc = np.array([1,2,3])

In [20]:
print(abc.ndim)

1


In [21]:
print(abc.shape)

(3,)


In [23]:
b = np.array([[0,1,2],[3,4,5]])

In [24]:
print(b.ndim)
print(b.shape)

2
(2, 3)


In [33]:
## 배열 인덱싱

In [25]:
a = np.array([1,2,3,4])

In [26]:
a[2]

3

In [27]:
a[-1]

4

In [28]:
b[0,0]

0

In [29]:
b[-1,-1]

5

In [30]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True,False,True,False,True,False,True,False,True,False])
a[idx]

array([0, 2, 4, 6, 8])

In [32]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [34]:
## 배열 슬라이싱

In [35]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
a[0,:]

array([0, 1, 2, 3])

In [38]:
a[:,1]

array([1, 5])

In [39]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [40]:
## numpy 데이터 타입

In [42]:
d = np.array([1,2,3], dtype='f')
d.dtype

dtype('float32')

In [43]:
## numpy inf, non

In [44]:
np.array([0,1,-1,0]) / np.array([1,0,0,0])

<ipython-input-44-720e9e2d83ea>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])
<ipython-input-44-720e9e2d83ea>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [45]:
np.log(0)

<ipython-input-45-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [46]:
np.exp(-np.inf)

0.0

In [47]:
## numpy zeros, ones, arange

In [49]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [50]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
c = np.zeros((5,2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [52]:
e = np.ones((2,3,4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [56]:
## 전치(transpose) 연산 - 행과 열 바꾸기

In [57]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
## 배열의 크기 변환

In [59]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
## 배열의 연산

In [63]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
x, y

(array([    1,     2,     3, ...,  9998,  9999, 10000]),
 array([10001, 10002, 10003, ..., 19998, 19999, 20000]))

In [64]:
z = x + y
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [65]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [66]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [67]:
10**a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [68]:
np.log(a+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [70]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
100*x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [72]:
## 차원 축소 연산

In [77]:
x = np.arange(1,5)
x

array([1, 2, 3, 4])

In [78]:
np.sum(x)

10

In [79]:
x.sum()

10

In [81]:
x.min()

1

In [82]:
x.max()

4

In [83]:
x.argmin() # 최소값의 위치

0

In [84]:
x.argmax() # 최대값의 위치

3

In [85]:
y = np.array([1,2,3,1])
y

array([1, 2, 3, 1])

In [86]:
y.mean()

1.75

In [88]:
np.median(y)

1.5

In [89]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [90]:
x.sum()

6

In [91]:
x.sum(axis=0)

array([3, 3])

In [92]:
x.sum(axis=1)

array([2, 4])

In [93]:
## numpy 기술 통계

In [94]:
np.var(x)

0.25

In [95]:
np.std(x)

0.5

In [96]:
## numpy 난수 생성

In [97]:
# 0~1 사이의 균일 분포
np.random.rand(10)

array([0.14075103, 0.88645544, 0.93072228, 0.25614066, 0.23388753,
       0.08543795, 0.15026951, 0.36229996, 0.80303654, 0.21257265])

In [98]:
np.random.rand(3,2)

array([[0.12162434, 0.75321201],
       [0.97585384, 0.15198073],
       [0.43304914, 0.74146056]])

In [99]:
# 정수 균일 분포
np.random.randint(10,20,size=10)

array([19, 17, 13, 12, 18, 10, 15, 14, 16, 19])

In [100]:
np.random.randint(10,20,size=(3,5))

array([[14, 12, 12, 17, 14],
       [12, 14, 16, 16, 16],
       [15, 14, 19, 11, 10]])